[runtime]
current_theme = "dark_theme"

[light_theme]
wallpaper = "~/Pictures/PFP45.jpg"
theme-gtk = "Adwaita"
theme-qt = "Adwaita"
pointer = "Bibata-Modern-Ice"
icons = "Adwaita"

[dark_theme]
wallpaper = "~/Pictures/Tokyo-Ghoul-Wallpaper-For-PC.jpg"
theme-gtk = "Dracula-standard-buttons"
theme-qt = "Adwaita-Dark"
pointer = "Bibata-Modern-Classic"
icons = "BigSur-black-dark"
